source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GSSimpleImage_Example', :exclusive => true do
  pod "GSSimpleImage", :path => "../"
  pod 'MBProgressHUD', '~> 0.9.2'
end

target 'GSSimpleImage_Tests', :exclusive => true do
  pod "GSSimpleImage", :path => "../"

  pod 'Quick', '~> 0.8.0'
  pod 'Nimble', '3.0.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
